### ISSUE TITLE
it wont load :(

### ISSUE THREAD

**Issue by ghost** [Trojaner/text-generation-webui-stable_diffusion#3]
please help me 

Traceback (most recent call last):
  File "D:\ei2\ai\text-generation-webui-main\modules\extensions.py", line 36, in load_extensions
    exec(f"import extensions.{name}.script")
  File "<string>", line 1, in <module>
  File "D:\ei2\ai\text-generation-webui-main\extensions\stable_diffusion\script.py", line 5, in <module>
    from .context import GenerationContext, get_current_context, set_current_context
  File "D:\ei2\ai\text-generation-webui-main\extensions\stable_diffusion\context.py", line 5, in <module>
    from .sd_client import SdWebUIApi
  File "D:\ei2\ai\text-generation-webui-main\extensions\stable_diffusion\sd_client.py", line 7, in <module>
    from webuiapi import WebUIApi
ModuleNotFoundError: No module named 'webuiapi'

i dont know what to do

**Comment by GGuussss** [comment]
I m using oobabooga
On windows, I had same problem.

open a terminal in your "text-generation-webui-main" folder
type :
`.\cmd_windows.bat`
on the venv prompt you can type :
`pip install -r .\extensions\stable_diffusion\requirements.txt`

**Comment by Trojaner** [comment]
@GGuussss is right. Closing as he posted the related fix.
